name: "Publish new release"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

  workflow_dispatch:
    inputs:
      version:
        description: 'Provide release version'
        type: string
        required: true

jobs:
  release:
    name: Publish new release
    runs-on: macos-13
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Install Bot SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v4.1.1
      - name: Extract version from branch name (for release branches)
        run: |
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
            VERSION=${BRANCH_NAME#release/}
            echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          fi
      - uses: ./.github/actions/ruby-cache
      - name: "Fastlane - Publish Release"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
        run: bundle exec fastlane publish_release version:${{ env.RELEASE_VERSION }} --verbose
